
services:
  - 'mysql:8.0.18'
variables:
  MYSQL_HOST: localhost
  MYSQL_DATABASE: NoteDB
  MYSQL_CI_URL: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}
  MYSQL_ROOT_PASSWORD: yourpassword
image: "maven:3.5.2-jdk-8"
maven-build:
           script: "mvn package"
           stage: build
maven-test:
           script: "mvn test"
           stage: test
stages:
       - test
       - build